apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: jhordycg/observability-fluentd
          ports:
            - containerPort: 24224
            - containerPort: 5140
          volumeMounts:
          - mountPath: /fluentd/log
            name: fluentd-log
          - mountPath: /fluentd/etc/fluent.conf
            name: fluentd-config
            readOnly: false
      volumes:
        - name: fluentd-log
          emptyDir: {}
        - name: fluentd-config
          configMap:
              defaultMode: 420
              name: fluentd-config

