apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  namespace: development
spec:
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: jhordycg/observability-first:latest
        ports:
        - containerPort: 8080
