apiVersion: v1
kind: Service
metadata:
  name: first-app
  namespace: development
spec:
  selector:
    app: first-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30800
  type: NodePort