apiVersion: v1
kind: Service
metadata:
  name: fluentd-persistence
  namespace: monitoring
  labels:
    app: fluentd-persistence
spec:
  selector:
    app: fluentd-persistence
  ports:
  - port: 3100
    targetPort: 3100
    nodePort: 30600
  type: NodePort