global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'first-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['first:8080']

  - job_name: 'second-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['second:8081']

  - job_name: 'jaeger-tracing'
    static_configs:
      - targets: ['jaeger-query:16687']