apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-persistence
  namespace: monitoring
  labels:
    app: jaeger-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-persistence
  template:
    metadata:
      labels:
        app: jaeger-persistence
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.12.1
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: "single-node"
            - name: http.host
              value: "0.0.0.0"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "false"
          volumeMounts:
            - name: elsearch-persistence
              mountPath: /usr/share/elasticsearch/data

      volumes:
        - name: elsearch-persistence
          emptyDir: {}