# Prometheus - Metrics

apiVersion: 1
datasources:
  - uid: uid_prometheus
    editable: false
    name: Prometheus Metrics
    type: prometheus
    access: proxy
    httpMethod: POST
    url: http://prometheus:9090
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceId
          datasourceUid: uid_jaeger
        - name: traceId
          url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'
